version: '3'

services:
   fritzlog:
     container_name: fritzlog
     labels:
       - "com.centurylinklabs.watchtower.enable=false"
     build:
       context: ./
       dockerfile: Dockerfile
     environment:
       - FB_URL=$URL
       - FB_USERNAME=$USERNAME
       - FB_PASSWORD=$PASSWORD
     restart: unless-stopped
