on:
  pull_request:
  push:
    branches: [main]

jobs:
  hadolint:
    runs-on:
      - ubuntu-latest
    container: pipelinecomponents/hadolint:0.10.1
    steps:
      - uses: actions/checkout@v3
      - name: Run hadolint
        run: hadolint Dockerfile
