on:
  pull_request:
  push:
    branches: [main]

jobs:
  hadolint:
    runs-on:
      - docker
    container: hadolint/hadolint:latest-alpine
    steps:
      - uses: actions/checkout@v3
      - name: Run hadolint
        run: hadolint Dockerfile
